name: Build and Test

on:
  workflow_dispatch:
  push:
    # branches:
    #   - main

permissions:
  contents: read
  id-token: write

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0

      - name: clone guac-data
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0
        with:
          repository: 'guacsec/guac-data'
          ref: 'main'
          path: 'guac-data'

      - name: GUAC Ingestion - Demo
        uses: ./
        continue-on-error: true
        with:
          files: ./guac-data/docs/spdx/spdx_vuln.json
          # files: ./guac-data/top-dh-sboms
          api-addr: https://demo.api.dev.kusari.cloud
          client-id: ${{ secrets.KUSARI_CLIENT_ID_DEMO }}
          client-secret: ${{ secrets.KUSARI_CLIENT_SECRET_DEMO }}
          token-url: https://auth.dev.kusari.cloud/oauth2/token

      - name: last step
        shell: bash
        run: |
          echo "This runs after GUAC ingestion"
